### PR TITLE
Add exemplary data, templates, & script for config screens

### PR DESCRIPTION
**Pull request by briandominick**
I think this demo should be pretty straightforward.

If you pull this branch and run the instructions in the new `README.adoc` file, you it will generate some source based on the files in `_data/`, which should be pretty self-explanatory, even though I'm taking guesses at folders, categories, and IDs of stuff, kind of a mix of my conventions and the existing conventions in the codebase.

If you don't get a chance or if you run into trouble (I'm assuming you have Ruby installed and have been using Ruby Asciidoctor for conversions), I'll happily do a demo of this in action. Everything will get installed in one step and you should be ready to parse with the command.

### CODE REVIEW

**Comment by ajw1970** [comment]
Very interesting, thank you. I just had to use yaml instead of yml for the _ops_build-docs.yaml file when running liquidoc 

Exciting to see what you've got going here! Thank you for putting this together.

I'll want to schedule a call to discuss this further. For the sake of this example, I'd want to adjust a few things. 

For instance, each configuration should have it's own images folder. 

We wouldn't use a single template for each either. There will be large parts that might be consistent for each depending on how be break things up but there will be variations. Looks to me like this is all still just configurable once I learn this system though.

**Comment by ajw1970** [comment]
Seems that what you've done here is create dependency injection system that sits in front of all of the other open tooling?

**Comment by briandominick** [comment]
Yeah it's all configurable of course. I didn't know what would be the most appropriate structure or naming conventions. My approach to this stuff seems radically different from yours. For instance, I would never spread images across multiple buckets, but we of course can handle that. I was assuming we could (and should) do some migration up front (which I tried to make an example of with the images). If that's not possible or preferred, we can work around it.

I think the more we are trying to conform my platform to your conventions, the more design work you'll need to do, because I may not be capable of that reorientation from an information architecture perspective, but LiquiDoc Ops can definitely meet you where you're at.

**Comment by briandominick** [comment]
As for the "dependency injection system", do you mean when it copies images to where we want them? That's a pretty big first step in my builds. That way you can source however and wherever you want, and we'll get it all where Asciidoctor/Jekyll need things for the build. We can do anything we want in the untracked `_build/` directory. I sometimes move images in there for the Asciidoctor PDF builds and then copy the images and those PDFs to a second place for the site deployment.

Those are "assets" though, in my lingo. The other _dependency_ action that's taking place here is less novel -- LiquiDoc pulls in Jekyll, Asciidoctor, and all the other dependencies you need. That `bundle install` command is magical.

**Comment by ajw1970** [comment]
> As for the "dependency injection system", do you mean when it copies images to where we want them? 

No... that you're gathering data first then generating files referencing that data so that those files are formatted and injected with necessary data. 
 
> That `bundle install` command is magical.

Yes... that part. You're standing in front of the AsciiDoctor/Jekyll system and building things they way they will need them so that  content authors don't have to know as many technical details. If I'm seeing this correctly.

I'll want to be sure those content pieces are broken up into bite size pieces.

**Comment by ajw1970** [comment]
> My approach to this stuff seems radically different from yours. For instance, I would never spread images across multiple buckets, but we of course can handle that. 

I wouldn't either but when we make changes we do it to one config at a time. We can only build at most 2-3 of these at a time physically due to the size of the factory. 

If we didn't split them up by config, it would be harder to capture pre-ship screens from a machine to update the images we will reference in the manual. 

When it comes to normal images, those will all be in one folder per manual or maybe one per manual section. 

These full screen captures are a unique thing. I was mostly using those so you can see how there are variations from one main screen to another even though they are all in essence one product.

**Comment by briandominick** [comment]
> If we didn't split them up by config, it would be harder to capture pre-ship screens from a machine to update the images we will reference in the manual.

Yeah this is exactly the experiential knowledge that's going to bridge the gap between my assumptions and what will actually work for you. But the "liquid" in LiquiDoc is intentional -- my framework will definitely conform to these needs around sourcing. The only downside is I'm less likely to already have build scripting templates to perform some of these operations, but those aren't hard to write. We just need to architect it carefully.

Re the dependency injection magic, let me clarify some of this, because it's key to the operation, and I agree you're going to want to be confident in that process and what it leaves you with. In fact, the more of this up-front ops we do, the more dependent you'll be on the system doing it.

> You're standing in front of the AsciiDoctor/Jekyll system and building things they way they will need them so that content authors don't have to know as many technical details. If I'm seeing this correctly.

This does not describe the `bundle install` command but the `liquidoc` command, or at least the most interesting part of the liquidoc command.

The `bundle exec` at the beginning just says to use the Ruby dependencies listed in the `Gemfile.lock` file, so you are sure to be using the exact stack I developed and tested with. Then it uses that stack to execute the command that performs the asset moves.

But yes, after the stage we're demonstrating now, the Asciidoctor render builds would occur. We would generate PDFs and then build the HTML sites with Jekyll/Asciidoctor _using `_build/` as the base directory, and we dump them into further subdirectories of `_build/`. Then that's our set of artifacts to deploy wherever we choose. But the "prebuild" phase results in a perfect AsciiDoc codebase under `_build/` so we can perform further ops. LiquiDoc is really just coordinating Jekyll and Asciidoctor commands from that point forward, with maybe a few more asset moves at the end.

The only truly novel functionality of LiquiDoc is scripting a series of Liquid template parses and then it enables some pretty hefty ingesting of data into Asciidoctor.

**Comment by ajw1970** [comment]
Thank you for the clarifications.

**Pull request merged**
