### PR TITLE
Expand data structs

### PR DESCRIPTION
**Pull request by briandominick**
I put this together yesterday and hoped to flesh it out a little more today, but I am probably only going to have enough time to write this up for now, because it isn't fully self-explanatory. I wanted to show you the structure of this file and tell you what it does so you can determine if it seems manageable.

What I'm adding here is an attempt to capture what is reflected by the navigation in Issue #7 and [ProFabriduct Operation Manual](https://github.com/mestekmachinery/Machine_Manuals/blob/main/ProFabriduct/Operation/IPI027V02_PDoperation.adoc) to give you some idea of what a product manifest file looks like.

I created a `content/` path for each of the 2 starting brands. So obviously any files distinct to those brands and their products go into these paths. There will also be a `common/` path, where all the shared AsciIDoc files will go.

Each _product_ will have a manifest file. I normally also create a global volumes file to define the artifacts we are going to produce, and I also include a `domains` object that is for subcategories within a product's docs. These seem to align very consistently in your application, so I am using `volumes` on a per-product basis, and they will parallel the concept of domains, if this works for us.

What this means is we can generate a PDF edition of each volume, and we can also break the left-side nav menu down by these volumes. If this is perfectly parallel, then we should just combine these concepts.

This doesn't mean everything we classify as a "volume" needs to have a PDF edition or needs to appear in the web portal, but if the buckets we're putting content in break down consistently between web and PDF, we are in business and can streamline this as I have tried to represent in the `_manifest.yml` file for `ProFabriduct`.

Obviously the slugs/IDs I'm making up for things can be changed to whatever you like. The bigger issue is the structure of this file.

Each topic entry is a web page or a chapter/section in a manual. 

We track this metadata (title and anything else we want) so we have a central registry.

LiquiDoc parses this file into many things, including.

1. nav menus for each product's content
1. topic metadata to be included by every topic file
2. xref attributes like I described recently, so our xrefs are always up to date

At the top of every .adoc topic file, we will have an include that draws attributes (including the title) from a topic-metadata file. So we are truly single-sourcing all of this, and we only need to keep track of it in one place.

The `volumes` object at the bottom of this file can accept a lot more information about each volume. We can name the output files, give them alternate names for their PDFs or their nav-menu entries, etc.

One odd thing about this file is the way I nest subtopics. You will see that all topics are actually registered on the same level, and then nesting is indicated by listing the slugs for subtopics as `subtopics:` of the parent, and then they are represented again below.

I did this not because it is the superior way of sourcing this information -- the alternative is to just have...

```yaml
- title: Some Title
  slug: some-title
  subtopics:
    - title: Some Subtopic Title
      slug: some-subtopic-title
    - title: Another Subtopic
      slug: another-subtopic
```

The problem is, it is inherently harder to code templates for the above format, and so far I have not made many templates that work well with nesting the full objects inside their parents. I do have some templates that match the other way of nesting (the way demonstrated in this commit). These templates are for all of the bullets I listed above (menus, topic metadata files, and xref attributes) and more. It would take a lot more hours to build solutions around the more-intuitive method for representing nested content.

We can talk about this, but former clients have found this method workable (with somewhat more complicated nesting, in fact), so if you think you can work with it, we're better off sticking with this.

I think that's enough explaining. I wish I had gotten farther, but this is almost exactly the structure my former clients Digi are using to maintain their complicated nested menus across multiple clients: https://www.digi.com/resources/documentation/digidocs/embedded/dey/3.0/cc8x/index.html

Their menus are very big, profoundly nested, and heavily reused across products.

### CODE REVIEW

**Comment by briandominick** [comment]
Ignore the multiple commits -- I rebased and force pushed, unsure why it just stacked the commits.

**Comment by ajw1970** [comment]
This looks good and sounds great. I don't see a problem with this way of handling subtopics. 

What's the next step?

**Comment by briandominick** [comment]
Great, since this format is acceptable, I'll start applying AsciiDocsy, plus some LiquiDoc Ops templating such as templates to turn the manifests into proper nav source. I should be able to get to that in the next day or so. I'll keep you posted.

We'll be building a rudimentary site then, and maybe some PDFs to boot. The templates for generating PDF indexes out for the manifests should be pretty close to this structure. I just need to modify how volumes are handled here, inside each product manifest, rather than in a global file. That's the biggest change and it's not huge.

**Comment by ajw1970** [comment]
Ok great. I was going to look at splitting up this file into included files by section: https://github.com/mestekmachinery/Machine_Manuals/blob/main/ProFabriduct/Controls/IPI004V07%20B%20%26%20R%20controls.adoc

Should I hold off on that for now?

**Comment by briandominick** [comment]
No that's a perfect task, as we want to get some of these documents chunked so we can serve them as topics in the site and reconstitute them for the PDFs.

If you take that document and break it down, put each resulting .adoc file in the `content/iowa-precision/pro-fabriduct/` and enter their "slugs" (the filename minus .adoc) and titles in the `_manifest.yml` file (or match them up with existing ones), we'll be very close to generating a nice chunk of the site.

**Comment by ajw1970** [comment]
I started this on branch breakup-controls-into-chunks

I'm currently working in the existing folder and was looking at moving some of these new adoc files over to the new content folder but how do we handle image paths?

Most of these new files will be shared files so they would go in common/ or content/common?

Where would their images go?

**Comment by briandominick** [comment]
Great questions. I'm moving the thread to Issue #12 so we have a place to dig in around the architecture.

**Pull request merged**
